insert into customer (custFName, custLName, address, pwd, username) values ('Lek', 'Pointer', '37094 Sommers Alley', 1234, 'lpointer0@fotki.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Kissee', 'Christopher', '56032 Paget Drive', 1234, 'kchristopher1@blogspot.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Shanna', 'MacFaul', '43 Walton Junction', 1234, 'smacfaul2@pbs.org');
insert into customer (custFName, custLName, address, pwd, username) values ('Durante', 'Joffe', '4 Harper Court', 1234, 'djoffe3@arstechnica.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Odell', 'Grewcock', '5499 Summit Pass', 1234, 'ogrewcock4@mtv.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Wylma', 'Brimm', '91700 Kedzie Lane', 1234, 'wbrimm5@lycos.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Krystalle', 'Cona', '3 Lyons Point', 1234, 'kcona6@bbb.org');
insert into customer (custFName, custLName, address, pwd, username) values ('Ricardo', 'Santori', '30 Pepper Wood Junction', 1234, 'rsantori7@booking.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Archer', 'Hartshorn', '47 Luster Lane', 1234, 'ahartshorn8@bravesites.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Dicky', 'Casazza', '92090 Briar Crest Terrace', 1234, 'dcasazza9@ifeng.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Sutherland', 'Gloucester', '0524 Portage Drive', 1234, 'sgloucestera@bandcamp.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Pearla', 'Laviss', '762 American Ash Street', 1234, 'plavissb@sphinn.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Rhody', 'Swate', '98 Prairieview Court', 1234, 'rswatec@earthlink.net');
insert into customer (custFName, custLName, address, pwd, username) values ('Chere', 'Gavaran', '23 Bunker Hill Way', 1234, 'cgavarand@amazonaws.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Ardelia', 'Karpinski', '63 Dexter Point', 1234, 'akarpinskie@gnu.org');
insert into customer (custFName, custLName, address, pwd, username) values ('Consalve', 'Ritchings', '85 Graedel Center', 1234, 'critchingsf@github.io');
insert into customer (custFName, custLName, address, pwd, username) values ('Gisele', 'Zimek', '78021 Northwestern Circle', 1234, 'gzimekg@miitbeian.gov.cn');
insert into customer (custFName, custLName, address, pwd, username) values ('Farica', 'Cameron', '68991 North Park', 1234, 'fcameronh@freewebs.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Adrea', 'Girhard', '6248 Garrison Park', 1234, 'agirhardi@ihg.com');
insert into customer (custFName, custLName, address, pwd, username) values ('Katinka', 'Dimelow', '5 Briar Crest Alley', 1234, 'kdimelowj@usa.gov');
